In [1]:
import pandas as pd 
import numpy as np
import sqlite3

In [2]:
# Data Import: db file to pandas, storing each table to a separate df

# Connect to SQLite database
conn = sqlite3.connect('../db/customer_churn.db')

# sql query to Get all table names
sql_query = """
        SELECT name
        FROM sqlite_master
        WHERE type='table';
"""

# read sql query in pandas
tables = pd.read_sql(sql_query, conn)

# create dataframe for each table
for table_name in tables['name']:
    df = pd.read_sql(f"SELECT * FROM {table_name}", conn) # Read table into dataframe
    globals()[f"df_{table_name}"] = df                    # Create dynamic dataframe name
    print(f"Created dataframe: df_{table_name}")

# Close connection
conn.close()

Created dataframe: df_db_customer
Created dataframe: df_db_subscription
Created dataframe: df_db_support

In [3]:
# Print table names and column names
conn = sqlite3.connect('customer_churn.db')

for table_name in tables['name']:
    print(f"\nTable Name: {table_name}")
    # Get column information
    columns_query = f"PRAGMA table_info({table_name});"
    columns = pd.read_sql(columns_query, conn)
    print("Columns:")
    print(columns['name'].tolist())

# Close connection
conn.close()

Table Name: db_customer
Columns:
[]

Table Name: db_subscription
Columns:
[]

Table Name: db_support
Columns:
[]

In [5]:
df_db_customer.head()

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [6]:
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     str
 1   name        21 non-null     str
 2   country     18 non-null     str
 3   state       21 non-null     str
 4   gender      21 non-null     str
 5   dob         21 non-null     str
 6   interests   4 non-null      str
 7   pincode     0 non-null      object
dtypes: object(1), str(7)
memory usage: 1.4+ KB

In [ ]:
# remove or drop intrest and pincode columns
# rename the column - name to customer name
# change the datatype of column - dob
# standardization of column - gender
# fill missing values in column - country

In [8]:
# remove or drop intrest and pincode columns

df_db_customer.drop(columns=['interests' , 'pincode'] , inplace=True)

In [11]:
# rename the column - name to customer name
df_db_customer.rename(columns = {'name':'customer_name'},inplace=True)

In [12]:
# change the datatype of column - dob
df_db_customer["dob"] = pd.to_datetime(df_db_customer["dob"])

In [14]:
# standardization of column - gender
df_db_customer['gender'].unique()

<StringArray>
['Male', 'Female', 'Women', 'Men']
Length: 4, dtype: str

In [15]:
df_db_customer['gender'] = df_db_customer['gender'].replace({'Men' : 'Male' , 'Women' : 'Female'})

In [17]:
# fill missing values in column - country
df_db_customer[['country' , 'state']]

   country          state
0    India    Maharashtra
1    India      Karnataka
2    India          Delhi
3    India       Nagaland
4    India          Delhi
5      NaN          Delhi
6    India      Meghalaya
7    India      Rajasthan
8      NaN      Kathmandu
9    Nepal      Kathmandu
10   India    Maharashtra
11   India      Karnataka
12     NaN      Telangana
13   India      Meghalaya
14   India  Uttar Pradesh
15   India          Delhi
16   India      Meghalaya
17   India      Rajasthan
18   India      Telangana
19   India  Uttar Pradesh
20   India    Maharashtra